name: universal-release

on:
  push:
    tags:
      - 'v*'   # π.χ. v0.2.0

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            rid: win-x64
            zip: Soundboard.Universal-${{ github.ref_name }}-win-x64.zip
          - os: ubuntu-latest
            rid: linux-x64
            zip: Soundboard.Universal-${{ github.ref_name }}-linux-x64.zip
          - os: macos-latest
            rid: osx-x64
            zip: Soundboard.Universal-${{ github.ref_name }}-osx-x64.zip
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Publish (self-contained)
        run: dotnet publish -c Release -r ${{ matrix.rid }} --self-contained true -p:PublishSingleFile=false -p:IncludeNativeLibrariesForSelfExtract=true

      - name: Copy config.json (if exists)
        shell: bash
        run: |
          PUBDIR="bin/Release/net8.0/${{ matrix.rid }}/publish"
          if [ -f config.json ]; then
            cp config.json "$PUBDIR/config.json"
          fi

      # Zip με διαφορετικό τρόπο ανά OS
      - name: Zip (Windows)
        if: runner.os == 'Windows'
        run: |
          $pub="bin/Release/net8.0/${{ matrix.rid }}/publish/*"
          Compress-Archive -Path $pub -DestinationPath "${{ matrix.zip }}" -Force

      - name: Zip (*nix)
        if: runner.os != 'Windows'
        run: |
          cd "bin/Release/net8.0/${{ matrix.rid }}/publish"
          zip -r "${{ github.workspace }}/${{ matrix.zip }}" .

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.zip }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
